name: remaiapp
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  cloud_firestore: ^5.2.0
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.3
  google_sign_in: ^6.2.1
  camera: ^0.11.0+1
  http: ^1.2.2
  google_generative_ai: ^0.4.4
  image_picker: ^1.1.2
  path_provider: ^2.1.4
  flutter_spinkit: ^5.2.1
  firebase_storage: ^12.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#ffffff"

flutter:

  uses-material-design: true
  assets:
    - assets/
